name: Deploy to Onamae Rental Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20

      - name: Install dependencies
      - run: |
          npm install

      - name: Set up environment variables
        run: |
          # 環境変数を .env ファイルに書き込む
          echo "VITE_API_KEY=${{ secrets.CMS_API_KEY }}" >> .env
          echo "VITE_SERVICE_DOMAIN=${{ secrets.CMS_SERVICE_DOMAIN }}" >> .env

      - name: Build the project
      - run: |
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_DIR }}/
          local-dir: dist/
          protocol: ftp
